### ISSUE TITLE
Question / Request for expressive-pipeline-from-config

### ISSUE THREAD

**Issue by manuakasam** [zendframework/zend-expressive-tooling#18]
So I'm trying to get my head around as to how this tool would be used.

Assuming I am using a modular approach to an expressive application. I now am adding a new route to the config. Since I'm also using the programmatic approach, I'd have to re-run the script.

I can totally understand that I have to manually remove the `config/pipeline.php` and `config/routes.php`. However, I have huge troubles with constantly having to edit the `index.php` to remove the doubled includes.

So my request would be to add a potential flag to the generate command that would delete existing `config/pipeline.php` and `config/routes.php` as well as skipping the step to add the include lines to the `index.php`.

Alternatively my question: is what I'm doing simply a weird approach? Am I overlooking something, maybe a different command to update the programmatic routing/pipeline when using the modular approach?

**Comment by weierophinney** [comment]
We now have code in place that detects if either a `config/pipeline.php` or `config/routes.php` exists, and, if so, aborts execution.

As noted in another issue you've raised, this tool was intended as a one-time migration tool, not one to run over and over in the same project.

**Comment by manuakasam** [comment]
OK, that reasoning is perfectly fine :)

The need to re-run this basically comes from the fact that we're developing a system with multiple modules and the application can be created using a variable configuration of modules used.
Thus, during deployment, we'd create the application config to define what modules to use and then run the expressive tooling to get the pipeline and routes config written. This works flawlessly.

The main issue here was during development, as here the config may be rewritten multiple times. Didn't think it would be such a unique issue. Though we'll simply have to write our own script then. Thanks for the explanation!
