### ISSUE TITLE
Update CreateMiddleware to add a factory and register it

### ISSUE THREAD

**Issue by akrabat** [zendframework/zend-expressive-tooling#42]
It would be useful if the create middleware functionality could add a skeleton factory and register it in the module's ConfigProvider.

This should be optional, so controlled by a switch.

Ideally, this would work for all DICs, but at a minimum, it should work for Zend-ServiceManager!

**Comment by geerteltink** [comment]
> It would be useful if the create middleware functionality could add a skeleton factory and register it in the module's ConfigProvider.

Where should the factory be saved? I've seen people saving it in the same dir and others in a special Factory dir.

> Ideally, this would work for all DICs, but at a minimum, it should work for Zend-ServiceManager!

This should not be a problem as they all can handle the `'dependencies' => 'factories'` config options.

Something extra that came into my mind: It should remove the config cache after creating the file(s). _Not sure if this is already happening._

**Comment by akrabat** [comment]
> > It would be useful if the create middleware functionality could add a skeleton factory and register it in the module's ConfigProvider.
> Where should the factory be saved? I've seen people saving it in the same dir and others in a special Factory dir.

Same directory. As this is what the skeleton does for `HomePageFactory`. If people put it elsewhere, they can not use this tool or move it.

**Comment by svycka** [comment]
> Same directory. As this is what the skeleton does for HomePageFactory. If people put it elsewhere, they can not use this tool or move it.

maybe add config option for this? or ask for the first time.

**Comment by geerteltink** [comment]
@svycka Development has started here: #52. It's easier/better to discuss more options there.

**Comment by weierophinney** [comment]
Feature is now in the release-1.0.0 branch, and we'll do a new alpha once I've addressed #50 and #51.
