### ISSUE TITLE
Why not put factory definition in ConfigProvider

### ISSUE THREAD

**Issue by lowtower** [zendframework/zend-expressive-tooling#67]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-tooling/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-tooling/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

The `zend-expressive-tooling` command `handler:create` creates a `handler`, a `handler factory`, a `template` and a `config` file.
The `template` is made "visible" to the app in the `ConfigProvider` whereas the `factory` is defined in the `config` file `config/autoload/zend-expressive-tooling-factories.global.php`.

Why is the `factory` definition not put in the `ConfigProvider` as well?

**Comment by weierophinney** [comment]
Short answer: it's too difficult.

Longer answer:

We have no idea how the `ConfigProvider` is structured. It could have the entire definition within `__invoke()`. It might delegate it to different methods. It might exclude dependencies configuration entirely. 

The ConfigProvider class may not exist at all, depending on whether you're using a flat or modular structure.

Or it might not be where you're expecting it; this is particularly true when using multi-segment namespaces for modules.

As such, we chose the safest, most reliable route: pushing it into the autoloadable configuration.

In terms of templates being made visible to the app via the `ConfigProvider`, that's not necessarily true. We load the _entire_ configuration when determining if the template namespace exists, and actually raise an error if we cannot find the namespace in the configuration. We do not actually _add_ to the configuration in this case; we leverage existing configuration to determine where to place the template.

**Comment by michalbundyra** [comment]
@weierophinney Maybe we should try to add it to 'default' ConfigProvider. I mean it should work together with `module:create` commands, which creates module and `ConfigProvider`. Then `handler:create` command should check for that file and for that structure, and insert it there. In case of failure the error message will be displayed with information that it should be added manually into configuration.
It would be nice to keep configuration specific for a module in that module, not in the global configuration.

**Comment by weierophinney** [comment]
@webimpress Please see above: it's not just about locating the `ConfigProvider`, but also _not being able to rely on its internal structure_ (i.e., what methods are present, where dependencies configuration lives, etc.). I'd originally intended to go that route, but quickly realized that there are simply too many different approaches, and we'd never be able to account for even a small subset of them.

Users can move the entries to appropriate `ConfigProvider` implementations afterwards if desired.
